version: '3'
services:
  app:
    build: .
    ports:
    - 4000:4000/tcp
    volumes:
    - .:/opt/app
    stdin_open: true
    tty: true
    depends_on:
      - database
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: gbs_api_dev
